export const ALL_ARTICLES_REQUEST = "ALL_ARTICLES_REQUEST"
export const ALL_ARTICLES_SUCCESS = "ALL_ARTICLES_SUCCESS"
export const ALL_ARTICLES_FAIL = "ALL_ARTICLES_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const ARTICLE_REQUEST = "ARTICLE_REQUEST"
export const ARTICLE_SUCCESS = "ARTICLE_SUCCESS"
export const ARTICLE_FAIL = "ARTICLE_FAIL"
