export const ALL_NOTICES_REQUEST = "ALL_NOTICES_REQUEST";
export const ALL_NOTICES_SUCCESS = "ALL_NOTICES_SUCCESS";
export const ALL_NOTICES_FAIL = "ALL_NOTICES_FAIL";

export const NOTICE_REQUEST = "NOTICE_REQUEST";
export const NOTICE_SUCCESS = "NOTICE_SUCCESS";
export const NOTICE_FAIL = "NOTICE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";