export const ALL_SEMESTER_REQUEST = "ALL_SEMESTER_REQUEST";
export const ALL_SEMESTER_SUCCESS = "ALL_SEMESTER_SUCCESS";
export const ALL_SEMESTER_FAIL = "ALL_SEMESTER_FAIL";

export const ALL_SUBJECT_REQUEST = "ALL_SUBJECT_REQUEST";
export const ALL_SUBJECT_SUCCESS = "ALL_SUBJECT_SUCCESS";
export const ALL_SUBJECT_FAIL = "ALL_SUBJECT_FAIL";

export const SUBJECT_REQUEST = "SUBJECT_REQUEST";
export const SUBJECT_SUCCESS = "SUBJECT_SUCCESS";
export const SUBJECT_FAIL = "SUBJECT_FAIL";

export const CHAPTER_REQUEST = "CHAPTER_REQUEST";
export const CHAPTER_SUCCESS = "CHAPTER_SUCCESS";
export const CHAPTER_FAIL = "CHAPTER_FAIL";

export const QUESTIONS_REQUEST = "QUESTIONS_REQUEST";
export const QUESTIONS_SUCCESS = "QUESTIONS_SUCCESS";
export const QUESTIONS_FAIL = "QUESTIONS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";