export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'

export const NEW_COMMENT_REQUEST = 'NEW_COMMENT_REQUEST'
export const NEW_COMMENT_SUCCESS = 'NEW_COMMENT_SUCCESS'
export const NEW_COMMENT_FAIL = 'NEW_COMMENT_FAIL'
export const NEW_COMMENT_RESET = 'NEW_COMMENT_RESET'

export const UPDATE_DETAILS_REQUEST = "UPDATE_DETAILS_REQUEST"
export const UPDATE_DETAILS_SUCCESS = "UPDATE_DETAILS_SUCCESS"
export const UPDATE_DETAILS_FAIL = "UPDATE_DETAILS_FAIL"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL"

export const PURCHASE_REQUEST = "PURCHASE_REQUEST"
export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS"
export const PURCHASE_FAIL = "PURCHASE_FAIL"

export const ACTIVE_PURCHASE_REQUEST = "ACTIVE_PURCHASE_REQUEST"
export const ACTIVE_PURCHASE_SUCCESS = "ACTIVE_PURCHASE_SUCCESS"
export const ACTIVE_PURCHASE_FAIL = "ACTIVE_PURCHASE_FAIL"
export const CLEAR_ACTIVE_PURCHASE = "CLEAR_ACTIVE_PURCHASE"

export const CANCEL_PURCHASE_REQUEST = "CANCEL_PURCHASE_REQUEST"
export const CANCEL_PURCHASE_SUCCESS = "CANCEL_PURCHASE_SUCCESS"
export const CANCEL_PURCHASE_FAIL = "CANCEL_PURCHASE_FAIL"
export const CANCEL_PURCHASE_RESET = "CANCEL_PURCHASE_RESET"

export const DELETE_PURCHASE_REQUEST = "DELETE_PURCHASE_REQUEST"
export const DELETE_PURCHASE_SUCCESS = "DELETE_PURCHASE_SUCCESS"
export const DELETE_PURCHASE_FAIL = "DELETE_PURCHASE_FAIL"
export const DELETE_PURCHASE_RESET = "DELETE_PURCHASE_RESET"

export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
